projectType: shell
devBranchesRegex: "master|support\\/.+"
releaseBranchesRegex: "release\\/.+"
mavenSettingsXmlId: data-weave-maven-settings
slackChannel: data-weave-bot
enableSlackSuccessNotifications: true
enableSlackFailedTestsNotifications: true
junitTestResults: '**/build/test-results/test/*.xml, **/build/test-results/*.xml'
enableAllureTestReportStage: false
enableSonarQubeStage: false
enableNexusIqStage: false
enableScheduleTrigger: true
scheduleTriggerCommand : "@daily"
upstreamProjects:
  DataWeave/data-weave/support/2.9.x,
  DataWeave/data-weave-tooling-extra/master
jdkTool: OPEN-JDK11
additionalTestConfigs:
  jdk17:
    jdkTool: OPEN-JDK17
    environmentVariables:
      TEST_ENVIRONMENT: "jdk17"
  arm-jdk17:
    agentLabel: ubuntu-22.04-arm
    jdkTool: OPEN-JDK17
    environmentVariables:
      TEST_ENVIRONMENT: "arm-jdk17"
  jdk21:
    jdkTool: TEMURIN-JDK21
    environmentVariables:
      TEST_ENVIRONMENT: "jdk21"